root: true

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true
  es2021: true

parser: "@babel/eslint-parser"

extends: 
  - "airbnb-base"
  - "plugin:jest/recommend"

rules: 
  no-console: 0
    import/extensions: 0